version: '2.4'

services:
  marmot-mysql:
    image: jumpserver/mysql:5
    container_name: marmot-mysql
    restart: always
    ports:
      - "3311:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    environment:
      DB_PORT: $DB_PORT
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - file-network
  marmot-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: jms_es
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      cluster.name: docker-cluster
      discovery.type: single-node
      network.host: 0.0.0.0
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "true"
      TAKE_FILE_OWNERSHIP: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: $BOOTSTRAP_TOKEN
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: "curl -sL http://localhost:9200 > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - file-network
networks:
  file-network:
    external: true
